name: Run Postman Collection on Multiple OS

on: 
  # push:
  #   branches:
  #     - main
  # pull_request:
  schedule:
    - cron: '55 15 * * *'

jobs:
  postman-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman collection
      run: |
        newman run postman/RestCountries.postman_collection.json
