name: Run Postman Collection on Multiple OS

on: 
  # push:
  #   branches:
  #     - main
  # pull_request:
  schedule:
    - cron: '55 15 * * *'

jobs:
  postman-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Newman and HTML reporter
      run: npm install -g newman@latest newman-reporter-htmlextra@latest

    - name: Cleanup old reports (Ubuntu/macOS)
      run: |
        if [ -d newman ] && [ "$(ls -A newman/*.html 2>/dev/null)" ]; then
          ls -t newman/*.html | tail -n +6 | xargs rm --  # Keep the latest 5 reports
        else
          echo "No HTML reports to clean up."
        fi
      shell: bash
      if: runner.os != 'Windows'

    - name: Cleanup old reports (Windows)
      run: |
        if (Test-Path "newman") {
          $reports = Get-ChildItem "newman\*.html" | Sort-Object LastWriteTime -Descending
          if ($reports.Count -gt 5) {
            $reports | Select-Object -Skip 5 | Remove-Item -Force  # Keep the latest 5 reports
          } else {
            Write-Host "No HTML reports to clean up."
          }
        } else {
          Write-Host "Directory 'newman' does not exist. Skipping cleanup."
        }
      shell: powershell
      if: runner.os == 'Windows'

    - name: Run Postman collection and generate HTML report
      run: npx newman run postman/RestCountries.postman_collection.json --reporters htmlextra --reporter-htmlextra-export newman/report-${{ matrix.os }}.html

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: postman-html-report-${{ matrix.os }}
        path: newman/report-${{ matrix.os }}.html
